/*
 * Copyright 2018, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AddressSpaceListerExpansion allows custom methods to be added to
// AddressSpaceLister.
type AddressSpaceListerExpansion interface{}

// AddressSpaceNamespaceListerExpansion allows custom methods to be added to
// AddressSpaceNamespaceLister.
type AddressSpaceNamespaceListerExpansion interface{}
