/*
 * Copyright 2018, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	enmassev1alpha1 "github.com/enmasseproject/enmasse/pkg/client/clientset/versioned/typed/enmasse/v1alpha1"
	iotv1alpha1 "github.com/enmasseproject/enmasse/pkg/client/clientset/versioned/typed/iot/v1alpha1"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	EnmasseV1alpha1() enmassev1alpha1.EnmasseV1alpha1Interface
	// Deprecated: please explicitly pick a version if possible.
	Enmasse() enmassev1alpha1.EnmasseV1alpha1Interface
	IotV1alpha1() iotv1alpha1.IotV1alpha1Interface
	// Deprecated: please explicitly pick a version if possible.
	Iot() iotv1alpha1.IotV1alpha1Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	enmasseV1alpha1 *enmassev1alpha1.EnmasseV1alpha1Client
	iotV1alpha1     *iotv1alpha1.IotV1alpha1Client
}

// EnmasseV1alpha1 retrieves the EnmasseV1alpha1Client
func (c *Clientset) EnmasseV1alpha1() enmassev1alpha1.EnmasseV1alpha1Interface {
	return c.enmasseV1alpha1
}

// Deprecated: Enmasse retrieves the default version of EnmasseClient.
// Please explicitly pick a version.
func (c *Clientset) Enmasse() enmassev1alpha1.EnmasseV1alpha1Interface {
	return c.enmasseV1alpha1
}

// IotV1alpha1 retrieves the IotV1alpha1Client
func (c *Clientset) IotV1alpha1() iotv1alpha1.IotV1alpha1Interface {
	return c.iotV1alpha1
}

// Deprecated: Iot retrieves the default version of IotClient.
// Please explicitly pick a version.
func (c *Clientset) Iot() iotv1alpha1.IotV1alpha1Interface {
	return c.iotV1alpha1
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.enmasseV1alpha1, err = enmassev1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.iotV1alpha1, err = iotv1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.enmasseV1alpha1 = enmassev1alpha1.NewForConfigOrDie(c)
	cs.iotV1alpha1 = iotv1alpha1.NewForConfigOrDie(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClientForConfigOrDie(c)
	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.enmasseV1alpha1 = enmassev1alpha1.New(c)
	cs.iotV1alpha1 = iotv1alpha1.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
