/*
 * Copyright 2018, EnMasse authors.
 * License: Apache License 2.0 (see the file LICENSE or http://apache.org/licenses/LICENSE-2.0.html).
 */

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	enmassev1alpha1 "github.com/enmasseproject/enmasse/pkg/apis/enmasse/v1alpha1"
	versioned "github.com/enmasseproject/enmasse/pkg/client/clientset/versioned"
	internalinterfaces "github.com/enmasseproject/enmasse/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/enmasseproject/enmasse/pkg/client/listers/enmasse/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AddressSpaceInformer provides access to a shared informer and lister for
// AddressSpaces.
type AddressSpaceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AddressSpaceLister
}

type addressSpaceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAddressSpaceInformer constructs a new informer for AddressSpace type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAddressSpaceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAddressSpaceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAddressSpaceInformer constructs a new informer for AddressSpace type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAddressSpaceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EnmasseV1alpha1().AddressSpaces(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EnmasseV1alpha1().AddressSpaces(namespace).Watch(options)
			},
		},
		&enmassev1alpha1.AddressSpace{},
		resyncPeriod,
		indexers,
	)
}

func (f *addressSpaceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAddressSpaceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *addressSpaceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&enmassev1alpha1.AddressSpace{}, f.defaultInformer)
}

func (f *addressSpaceInformer) Lister() v1alpha1.AddressSpaceLister {
	return v1alpha1.NewAddressSpaceLister(f.Informer().GetIndexer())
}
